name: Visual Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  visual-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install lost-pixel
      - run: npx playwright install chromium  # ← This is the new line!
      - run: npx lost-pixel
